enum MUSIC_QUERY_KEY_ENUM {
  USERS = "USERS",
  ARTISTS = "ARTISTS",
  ARTIST_DETAIL = "ARTIST_DETAIL",
  ALBUMS = "ALBUMS",
  ALBUM_DETAIL = "ALBUM_DETAIL",

  USER_DETAIL = "USER_DETAIL",
  GENRES = "GENRES",
  GENRES_DETAIL = "GENRES_DETAIL",
}

export default MUSIC_QUERY_KEY_ENUM;
