enum MUSIC_QUERY_KEY_ENUM {
  USERS = "USERS",
  ARTISTS = "ARTISTS",
  ARTIST_DETAIL = "ARTIST_DETAIL",
  ALBUMS = "ALBUMS",
  ALBUM_DETAIL = "ALBUM_DETAIL",

  USER_DETAIL = "USER_DETAIL",
  GENRES = "GENRES",
  GENRES_DETAIL = "GENRES_DETAIL",
  SONGS = "SONGS",
  SONG_DETAIL = "SONG_DETAIL",
  PLAYLIST = "PLAYLIST",
  PLAYLIST_DETAIL = "PLAYLIST_DETAIL",
  MUSIC_GENRE_STATS = "MUSIC_GENRE_STATS",
  USER_HISTORY = "USER_HISTORY",
  USER_HISTORY_DETAIL = "USER_HISTORY_DETAIL",
  TOTAL_COUNT = "TOTAL_COUNT",
  TRENDING_SONGS = "TRENDING_SONGS",
}

export default MUSIC_QUERY_KEY_ENUM;
