enum USER_QUERY_KEY_ENUM {
  ACCOUNTS = "ACCOUNTS",
  ROLES = "ROLES",
  ACCOUNT_DETAILS = "ACCOUNT_DETAILS",
  ROLE_DETAILS = "ROLE_DETAILS",
  VERIFY_EMAIL = "VERIFY_EMAIL",
}

export default USER_QUERY_KEY_ENUM;
